### ISSUE TITLE
Random CTD

### ISSUE THREAD

**Issue by sugardoggod** [m-vlad/Yggdrasil-VR#104]
Random crashes while playing

 - Yggdrasil VR version: 2.1-1
 - Storage type Yggdrasil VR is installed on: SSD
 - OS version: Windows 10
 - RAM:  16gb
 - CPU: AMD Ryzen 5 3500X
 - GPU: Nvidia  RTX 3060 12gb
 - Antivirus Dr.Web

[Quicksave0_78F95D9C_0_5661726772_Tamriel_000102_20240118215829_1_1.zip](https://github.com/CritLoren/Yggdrasil-VR/files/13982169/Quicksave0_78F95D9C_0_5661726772_Tamriel_000102_20240118215829_1_1.zip)
[crash-2024-01-18-21-59-48.log](https://github.com/CritLoren/Yggdrasil-VR/files/13982178/crash-2024-01-18-21-59-48.log)

**Comment by CritLoren** [comment]
Can you update Mu Joint Fix?

**Comment by sugardoggod** [comment]
> Can you update Mu Joint Fix?

I already have decent version installed.
Updated Engine Fixes, will be testing soon

**Comment by sugardoggod** [comment]
Updated engine fixes and adress library, been playing for hour and no crashes all good, thank you!
