### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by KateHanami** [m-vlad/Yggdrasil-VR#107]
nothing out of the ordinary, simply on D Drive (HDD) installing via Wabbajack

[Wabbajack.current.log](https://github.com/CritLoren/Yggdrasil-VR/files/14969038/Wabbajack.current.log)

 - Yggdrasil VR version: [whatever wabbajack installs]
 - Storage type Yggdrasil VR is installed on: [ D:\ drive 2TB HDD ]
 - OS version: [Windows Xlite] (windows 11 pro modified to remove bloatware)
 - RAM: [16gb - 8x2gb 1600mhz]
 - CPU: [AMD FX 9130 Eight core] (yes eight core is part of the name)
 - GPU: [not aplicable]
 - Antivirus [none] (thanks to Xlite)

**Additional context**

**Comment by CritLoren** [comment]
Hello, please report issues with the installation part on the discord not here. As far as your issue however i'd make sure you have enough free space in that C drive while it's installing the modlist.

**Comment by KateHanami** [comment]
as said above, it is installed on D drive, with enough extra space,
additionally, the same error happens multiple times, as I try to install the modlist it always gives the same error on the same step

**Comment by CritLoren** [comment]
but your wabbajack is on the C drive, so it's where it'll temporarily be extracting and patching files before it moves them to your folder.
