### ISSUE TITLE
CTD near Whiterun

### ISSUE THREAD

**Issue by QnoisX** [m-vlad/Yggdrasil-VR#12]
Game just crashes to desktop when near Whiterun.

**To Reproduce**
Load save and run along the road to Whiterun.

**Expected behavior**
CTD

**Screenshots**
Sorry, no way to take a screenshot.

**Save**
[CTD after this save.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9126790/CTD.after.this.save.zip)

**Crash log**
[crash-2022-07-16-21-17-48.log](https://github.com/m-vlad/Yggdrasil-VR/files/9126794/crash-2022-07-16-21-17-48.log)
[crash-2022-07-16-23-22-13.log](https://github.com/m-vlad/Yggdrasil-VR/files/9126795/crash-2022-07-16-23-22-13.log)

**Desktop (please complete the following information):**
 - OS version: [Windows 11]
 - RAM: [32gb]
 - CPU: [Ryzen 5950x]
 - GPU: [GeForce RTX 3090]
 - Storage type Yggdrasil VR is installed on: [SSD]
 - Antivirus [Windows Defender]

**Additional context**

**Comment by m-vlad** [comment]
One of them requires me to regen Occlusion, the other log might require me to do a patch between apocalypse and skeleton replacer HD, or remove the hat entirely from the pirate summon.

**Comment by m-vlad** [comment]
For the second issue, can you try loading this esp as late as possible?
[Skeleton Patch for Apocalypse.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9127565/Skeleton.Patch.for.Apocalypse.zip)

**Comment by QnoisX** [comment]
[CaptSkellie.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9136271/CaptSkellie.zip)
Working summon.

**Comment by m-vlad** [comment]
[Skeleton Patch for Apocalypse.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9139192/Skeleton.Patch.for.Apocalypse.zip)
Updated fix, see if this fixes things.

**Comment by m-vlad** [comment]
Found a solution for now, swapping the armour mesh to something else and removing the hat.
