### ISSUE TITLE
Caravan strike

### ISSUE THREAD

**Issue by QnoisX** [m-vlad/Yggdrasil-VR#18]
**Describe the bug**
The caravan drivers don't give an option to fast travel to other towns.  Only have options for storing and chatting about their town.

**To Reproduce**
1. Go to a caravan driver
2. Click on his body
3. Scroll down to ??? Good question.

**Expected behavior**
Caravan drivers normally will take you to any town in Skyrim for a small fee, even towns you haven't discovered.

**Screenshots**
![ScreenShot103](https://user-images.githubusercontent.com/109442605/179669257-9580bb93-0393-444c-9c3f-5d123bff77f7.png)

**Save**
Don't have a save nearby a driver atm.

**Crash log**
No crash, just drivers on strike.

**Desktop (please complete the following information):**
        OS: Microsoft Windows 11 Pro Insider Preview v10.0.25158
	CPU: AuthenticAMD AMD Ryzen 9 5950X 16-Core Processor            
	GPU #1: Nvidia GA102 [GeForce RTX 3090]
	GPU #2: Microsoft Basic Render Driver
	PHYSICAL MEMORY: 16.22 GB/31.91 GB

**Additional context**
No context, just sore feet from hoofing it to Markath.

**Comment by m-vlad** [comment]
If you wait around, does he get back on his carriage? it might be his package of being a driver is off duty.

**Comment by QnoisX** [comment]
Nah, he just stands next to the carriage.  Usually, when I approach after being gone a while, he's hopping off the driver's seat and another npc is climbing out of the back.  So, maybe he just doesn't like me in general.

**Comment by m-vlad** [comment]
Haven't tested but the condition for them to sit down was removed so this should be fixed. Reopen if you still have issues after 2.0-4
