### ISSUE TITLE
A purple Chicken in Whiterun near the brewery 

### ISSUE THREAD

**Issue by GingasVRFO** [m-vlad/Yggdrasil-VR#19]
**Describe the bug**
Purple Chicken

**To Reproduce**
Chicken?

**Expected behavior**
not be purple lol

**Screenshots**

![chicken](https://user-images.githubusercontent.com/67027574/179671010-5a69d856-5900-439b-bc56-2f078298bcc2.PNG)

**Desktop (please complete the following information):**
 - OS version: Windows 10
 - RAM: 32GB
 - CPU:9900KS
 - GPU: 3080ti
 - Storage type Yggdrasil VR is installed on: SSD

**Comment by m-vlad** [comment]
Happens if you disable the occlusion esp since that's what I piggy back off of. To load the creature asset merge.
