### ISSUE TITLE
Bannered Mare counts as trespassing at night

### ISSUE THREAD

**Issue by CameraBeard** [m-vlad/Yggdrasil-VR#2]
**Describe the bug**
The Bannered Mare was locked and counts as trespassing at night. Hulda gives me a bounty, so it isn't just a locked door, the game thinks I am trespassing.

**To Reproduce**
Enter the Bannered Mare at night (I'm assuming after 8 pm) It was 1 am when I tried

**Expected behavior**
Not to be trespassing.

**Screenshots**

**Save**
[saves.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9107662/saves.zip)

**Crash log**
If applicable, add a save to reproduce your problem. You can find them at `My Documents/My Games/Skyrim VR/SKSE/` where they'll be named something like `crash-2021-12-20-23-21-37.log`.

**Save**
If applicable, add save to reproduce your problem.

**Desktop (please complete the following information):**
 - OS version: Windows 10
 - RAM: 32GB Ram
 - CPU: i7-11800H
 - GPU: Nvidia RTX 3070
 - Storage type Narsil is installed on: SSD
 - Antivirus MalwareBytes, Windows Defender

**Additional context**

**Comment by m-vlad** [comment]
I went to the Bannered Mare on your save and it seemed to be locked, might be why it was seen as trespassing? I went in during the day and waited inside though and wasn't kicked out, so maybe with the removal of the trespass mod I added last minute this gets fixed. Will keep this here until the next hotfix update.

**Comment by m-vlad** [comment]
oh FYI, if a door of a shop/inn is closed, sneaking in *will* count as trespassing, that's by design. The issue would be more on why it's locked, but I don't see anything in my esps that could cause the door to lock itself, so I wonder if it's just vanilla behaviour?

**Comment by QnoisX** [comment]
I encountered the locked door also.  The side door wasn't locked, and they didn't seem to care that I was inside.  However, the alchemy shop did a weird thing.  I was buying stuff in the middle of the day.  After I finished, the vendor lady walked around the counter and started asking me to leave.  So, I left.  I'll grab a screenshot or make a save if it happens again.  Or just wait till the fix.

**Comment by m-vlad** [comment]
Oh it's possible you entered through the back door, which is why they would be kicking you out. I'm temporarily removing that mod anyway because there's some locations it covers that have entirely different layouts in Holds.
