### ISSUE TITLE
Undead Nature

### ISSUE THREAD

**Issue by Drift530** [m-vlad/Yggdrasil-VR#21]
A message appears saying the following:
"Your undead nature is known to everyone. Everyone will try to kill you"

It can be easily reproduced by walking near Nazarick.

[Save74_8B035B20_0_4472696674_Tamriel_000531_20220719200906_8_1.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9144449/Save74_8B035B20_0_4472696674_Tamriel_000531_20220719200906_8_1.zip)

**Comment by m-vlad** [comment]
I am even more confused now, i changed that message in xedit, is this something with the script..?

**Comment by m-vlad** [comment]
[2.0 - Additional Races.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9145114/2.0.-.Additional.Races.zip)
Can you replace the existing Additional Races entry with this and see if the message appears still?

**Comment by QnoisX** [comment]
No message when approaching the tomb with a normal character with this fix.  But can't seem to remove the debuff by wearing clothing as a skeleton.

**Comment by m-vlad** [comment]
So the "Feared Monster" effect is always active? Even if you use the necklace?

**Comment by m-vlad** [comment]
[2.0-4 - Additional Races.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9152079/2.0-4.-.Additional.Races.zip)
Try this then.

**Comment by QnoisX** [comment]
I couldn't find the necklace.

**Comment by m-vlad** [comment]
Fixed for now, might look into a better solution some other time, but the current fix works.
