### ISSUE TITLE
CTD outside Stonehollow in Wyrmstooth

### ISSUE THREAD

**Issue by django747** [m-vlad/Yggdrasil-VR#22]
**Describe the bug**
Traveling from the mountain path to the south side of Stonehollow in Wyrmstooth leads to a CTD.

**To Reproduce**
1. Load save.
2. Travel path to Stonehollow.
3. CTD

**Expected behavior**
It is expected to go into Stonehollow to finish the main quest for the Wyrmstooth expansion.

**Screenshots**
N/A

**Save**
[save.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9145038/save.zip)

**Crash log**
[crash-2022-07-19-22-05-14.log](https://github.com/m-vlad/Yggdrasil-VR/files/9145043/crash-2022-07-19-22-05-14.log)

**Desktop (please complete the following information):**
 - OS version: [e.g. Windows 11, Windows 10] Windows 10
 - RAM: [e.g. 16gb, 32gb] 32gb
 - CPU: [e.g. Intel i7-9750H] AMD Ryzen 7
 - GPU: [e.g. Nvidia RTX 2060 Mobile] Nvidia RTX 2070 SUPER
 - Storage type Yggdrasil VR is installed on: [e.g. SSD, HDD] SSD
 - Antivirus [e.g. Windows Defender, Bitdefender] Windows Defender

**Additional context**
The INI fix mentioned in the latest announcement was placed in the overwrite folder. No references to 'captain' were found in the crash log.

**Comment by m-vlad** [comment]
Confirmed fixed in the 2.0-4
