### ISSUE TITLE
vectorplexus error

### ISSUE THREAD

**Issue by anatole1234** [m-vlad/Yggdrasil-VR#23]
**Describe the bug**
Stuck during install saying that wabbajack cannot reach vectorplexus.com

**To Reproduce**
1. Click on install
2. wait for Yggdrasil VR.wabbajack finish extracting
3. refresh

**Expected behavior**
expected to download
it says http connect error to https://www.vectorplexus.com/favicon.ico

**Comment by m-vlad** [comment]
This list doesn't use files from Vector Plexus, I'd ask about support on the Wabbajack Discord.

**Comment by anatole1234** [comment]
> This list doesn't use files from Vector Plexus, I'd ask about support on the Wabbajack Discord.

odd. will do thank you
