### ISSUE TITLE
CTD almost every time I enter combat with humanoid enemies.

### ISSUE THREAD

**Issue by MidiRexxo** [m-vlad/Yggdrasil-VR#24]
**The Problem**
Every time I enter combat with humanoid enemies, no matter if they are goblins, humans, undead, I usually just crash with the same log it seems..

**To Reproduce**
1. Get seen by enemies
2. Gets attacked by enemies
3. Crashes to Desktop
4. -Has Pirate fix installed in overwrite-

**Expected behavior**
Just playing, pretty much.

**Screenshots**
sadly couldn't get any

**Save**
[https://www.mediafire.com/file/b0hpf6kva1febn0/Quicksave0_C0DB615A_0_4E69636B_AbandonedPrison01_000219_20220720023546_3_1.ess/file](url)

**Crash log**
[https://www.mediafire.com/file/u01d7aqnet9lr85/crash-2022-07-20-03-03-08.log/file](url)

**Desktop (please complete the following information):**
 - Windows 10 Enterprise 64bit
 - RAM: 64GB
 - CPU: Intel i5-1600kf
 - GPU: RTX 3060ti
 - Storage type Yggdrasil VR is installed on: SSD
 - Antivirus: Windows Defender

**Comment by m-vlad** [comment]
please just post saves and crash logs here, not on third party sites next time

**Comment by m-vlad** [comment]
can you go indoors and wait 31 games in day? It looks like the pirate crash all over again.

**Comment by MidiRexxo** [comment]
I can try waiting 31 ingame days in an interior, but that might starve and kill my character lol

**Comment by m-vlad** [comment]
Temporarily disable sunhelm first.

**Comment by MidiRexxo** [comment]
Combat has mostly fixed but for some reason I'm crashing pretty often in Solitude. Not sure if it's documented.
[crash-2022-07-20-23-30-22.log](https://github.com/m-vlad/Yggdrasil-VR/files/9155019/crash-2022-07-20-23-30-22.log)

**Comment by m-vlad** [comment]
Open a separate bug report. The issue here is still related to the pirates, which I've found a more long term solution for and will be shipped in the next hotfix.
