### ISSUE TITLE
"Water" isn't a visable inventory item and can seriously weigh you down.

### ISSUE THREAD

**Issue by zosologist** [m-vlad/Yggdrasil-VR#27]
**Describe the bug**
It is possible to craft "Water" at a cooking pot,  but there is no way to remove it as it does not show up in the inventory.
**To Reproduce**
1. Go to 'a cooking pot, I was specifically using the one at the Riverwood trader'
2. Click on 'Craft Water a whole bunch'
3. Open your Inventory and see that your carry weight has increased
4. It is now only possible to remove the "Water" from your inventory by crafting with it

**Expected behavior**
I would like to be able to remove the water from my pockets.

**Desktop (please complete the following information):**
 - OS version: Windows 11
 - RAM: 16gb
 - CPU: AMD Ryzen 5 3600
 - GPU: RTX 3080
 - Storage type Yggdrasil VR is installed on: NVME SSD
 - Antivirus Windows Defender

**Comment by m-vlad** [comment]
please post your save as well

**Comment by zosologist** [comment]
[Save77_8C65BE63_0_5661726772_RiverwoodRiverwoodTrader_000507_20220722224223_4_1.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9172573/Save77_8C65BE63_0_5661726772_RiverwoodRiverwoodTrader_000507_20220722224223_4_1.zip)

**Comment by m-vlad** [comment]
Fixed, "Water" should show in your inventory next hotfix.
