### ISSUE TITLE
Too many scrolls/encounters

### ISSUE THREAD

**Issue by QnoisX** [m-vlad/Yggdrasil-VR#36]
**Describe the bug**
Just a reminder that we're currently getting too many scrolls from loot.  Enemies drop on average half a dozen scrolls just from random encounters.  They also will use the scrolls in combat for some very unbalanced results. 

Reminder #2: the random encounters is set much too high.  You can't travel from one town to another without running into multiple large fights.  Changing "Extended Encounters" MCM from 50% to 15-20% would be ideal.

**To Reproduce**
1. Go to anywhere
2. Kill random npc or just loot the multiple corpses from fights
3. Scroll down to just all the scrolls

**Expected behavior**
Very few scrolls as loot, often zero.  At most 2 on caster types.  Also, rarer encounters in the wild.

**Screenshots**
![ScreenShot85](https://user-images.githubusercontent.com/109442605/182040450-0d5e5807-d9e0-436f-bfe4-f7c3dae5d3f1.png)

**Save**

**Crash log**

**Desktop (please complete the following information):**
	OS: Microsoft Windows 11 Pro Insider Preview v10.0.25151
	CPU: AuthenticAMD AMD Ryzen 9 5950X 16-Core Processor            
	GPU #1: Nvidia GA102 [GeForce RTX 3090]
	GPU #2: Microsoft Basic Render Driver
	PHYSICAL MEMORY: 15.39 GB/31.91 GB
 - Antivirus [Windows Defender]

**Additional context**

**Comment by m-vlad** [comment]
Removed the apocalypse distributed scrolls.

**Comment by m-vlad** [comment]
Will add an MCM Recorder for encounters
