### ISSUE TITLE
Companions Questline Broken

### ISSUE THREAD

**Issue by SPLUMBAR** [m-vlad/Yggdrasil-VR#38]
The mod “The Companions - Earn Your Stripes” is known to be bugged and never lets you progress the questline to becoming a werewolf, forcing you to do radiant quests eternally. This is a problem with the mod itself, the comments on Nexus say so.

**Comment by QnoisX** [comment]
The radiant quest requirement was set at 12 instead of 6.  I changed it back to 6.
[Merge - Conflict Resolution.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9239550/Merge.-.Conflict.Resolution.zip)
.

**Comment by QnoisX** [comment]
Didn't work.

**Comment by SPLUMBAR** [comment]
Confirmed that doing 12 radiant quests, instead of 6, after "Proving Honor" unlocks the next quest "The Silver Hand". Not broken, just listed incorrectly in the mod's description.
