### ISSUE TITLE
Werewolf body stands in front of me.

### ISSUE THREAD

**Issue by minipiwi** [m-vlad/Yggdrasil-VR#4]
**Werewolf body in front of me**
Whenever I transform into a werewolf, rather than having the body in me like whenever I'm a human, the body stretches in front of me, almost as if I was watching someone else in third person. Transforming is the only way I've had this issue.

**Images**
![20220714140901_1](https://user-images.githubusercontent.com/109307057/179054302-b90f2eeb-3a5d-4f71-8b1b-6572e7167f83.jpg)
![20220714140905_1](https://user-images.githubusercontent.com/109307057/179054361-d429c77b-144e-4869-9444-f42771dcd123.jpg)
![20220714140908_1](https://user-images.githubusercontent.com/109307057/179054380-a28a409c-bc24-4a42-948e-9495401d3864.jpg)
![20220714140912_1](https://user-images.githubusercontent.com/109307057/179054393-b1521881-dbc2-4134-aa8d-867cf000b613.jpg)

 - Windows 10
 - RAM: 16 gigs
 - CPU: Ryzen 7 2700x
 - GPU: Nvidea Rtx 3070ti OC
 - SSD
 - Antivirus Windows

**Additional context**
Idk if this might have anything to do with it but when i encountered beast blood, i choose the Wearbear option, but went into the MCM to change it back to werewolf.

**Comment by minipiwi** [comment]
Yep just tried them, didn't change anything.

**Comment by m-vlad** [comment]
Can you provide a save so I can look into this further?

**Comment by minipiwi** [comment]
I can't post it here since it says the file is not supported

**Comment by minipiwi** [comment]
I did another test with a new character and added the spell manually and I get the same results

**Comment by m-vlad** [comment]
put the save in a zip, that ought to let you post the file.

**Comment by minipiwi** [comment]
I know this is very late sorry about that but here;
[Save17_A77CC8B4_0_5661726772_Tamriel_000100_20220714174614_1_1.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9136507/Save17_A77CC8B4_0_5661726772_Tamriel_000100_20220714174614_1_1.zip)

**Comment by m-vlad** [comment]
Could i have the skse cosave as well? Thank you

**Comment by minipiwi** [comment]
[Save17_A77CC8B4_0_5661726772_Tamriel_000100_20220714174614_1_1.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9143103/Save17_A77CC8B4_0_5661726772_Tamriel_000100_20220714174614_1_1.zip)
sure thing! Sorry for not including it.

**Comment by m-vlad** [comment]
Installing the mod to use the Vanilla skeleton instead of the xp32 one fixed the issue.
