### ISSUE TITLE
Ai bug and every item spawn bug. help me please

### ISSUE THREAD

**Issue by nikipro098123** [m-vlad/Yggdrasil-VR#40]
so I downloaded SkyrimVR Yoggdrasil. and everything running smooth and fine, but when I entered the inn I saw every item on this sort of table dropped on the ground, and then I see an NPC who is leaning on air.

![skyrim bug](https://user-images.githubusercontent.com/110555319/182658184-d4248a2c-a7b0-49ff-a426-fc1ffc8ee553.PNG)

can someone help me, please?

**Comment by m-vlad** [comment]
Please follow the template when making bug reports. That said, that looks like a landscape issue, as in it's something I'll investigate later when I get a copy of the list running on SSE locally.

**Comment by nikipro098123** [comment]
ok. can I do something about it?
