### ISSUE TITLE
Clockwork CDT

### ISSUE THREAD

**Issue by MichailLavreek** [m-vlad/Yggdrasil-VR#45]
**Describe the bug**
Sometimes when you encounter gilded reanimation CDT will happen. Happens at least 20 times for me while I'm completing the story of Clockwork. At some point its become unavoidable for me to complete the quest without CDT. Fixed with disabling gilded reanimation in the MCM menu.

**To Reproduce**
1. Go to the Hall of The Elements
2. Clear location
3. Wait till Gilded are reanimated
4. Try to run through the location again, 100% you will encounter CDT.

If you use my save - all you need is run to the exit of the current location and you will have CDT shortly after.

**Expected behavior**
No CDT.

**Save**
[saves.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9274535/saves.zip)

**Crash log**
[crash-2022-08-04-08-56-16.log](https://github.com/m-vlad/Yggdrasil-VR/files/9274532/crash-2022-08-04-08-56-16.log)

**Desktop (please complete the following information):**
 - OS version:  Windows 10
 - RAM: 16gb
 - CPU: ryzen 3700
 - GPU:  RTX 1080 ti
 - Storage type Yggdrasil VR is installed on: SSD
 - Antivirus Windows Defender

**Additional context**
Needs to be fixed CDT's with gilded reanimation, or disabled gilded reanimation by default.

**Comment by QnoisX** [comment]
I made an MCM recording to automatically turn the Gilded respawn off from the start.  Should prevent the CTD error.
[0001_Clockwork .zip](https://github.com/m-vlad/Yggdrasil-VR/files/9313466/0001_Clockwork.zip)

**Comment by m-vlad** [comment]
I trust that mcm recorder script to work, if the bug reappears this can be reopened.
