### ISSUE TITLE
All Appraisal Magic Item - spell is not working

### ISSUE THREAD

**Issue by MichailLavreek** [m-vlad/Yggdrasil-VR#46]
**Describe the bug**
All Appraisal Magic Item: for next 30s learning an enchantment wont destroy and item.
Its clearly is not working how its suppose to be, I'm casting a spell, trying to learn enchant from item, item is destroyed in the process.

**To Reproduce**
1. Cast All Appraisal Magic Item
2. Try to learn the enchant from enchanted item on enchanters table

**Expected behavior**
Item is not destroyed

**Save**
here the save with character that has the spell and items that can be disenchanted, enchanters table is in the next room
[saves.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9274557/saves.zip)

**Desktop (please complete the following information):**

    OS version: Windows 10
    RAM: 16gb
    CPU: ryzen 3700
    GPU: RTX 1080 ti
    Storage type Yggdrasil VR is installed on: SSD
    Antivirus Windows Defender

**Comment by QnoisX** [comment]
I don't think time is frozen while in crafting menus.  Maybe the problem?  Might just remove this spell.  It just copies a perk.

**Comment by MichailLavreek** [comment]
> I don't think time is frozen while in crafting menus. Maybe the problem? Might just remove this spell. It just copies a perk.

Effect of the spell is still going when I trying to get an enchantment so not the time problem. Removing the spell is OK its not that important for me, just been told by Crit to create the bug report

**Comment by m-vlad** [comment]
It's fine I can adjust the spell to work, no need to remove it :)

**Comment by m-vlad** [comment]
[Overlord - Ordinator Patch.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9343868/Overlord.-.Ordinator.Patch.zip)
Can either of you two try this? It should apply the Ordinator perks for keeping items while disenchanting for 30 seconds, nothing more than that. I'm guessing the OG spell doesn't work because Ordinator does some funny stuff with enchanting tables once you get the gem dust perk.

**Comment by QnoisX** [comment]
That fix works and enables the gem sacrifice ability from Ordinator as well.
