### ISSUE TITLE
Visual Animated Enchants - "Soul Trap" enchantment causes CTD when equipped and drawn

### ISSUE THREAD

**Issue by DrDollaryDoo** [m-vlad/Yggdrasil-VR#5]
**Describe the bug**
Equipping and drawing a weapon with the "Soul Trap" enchantment causes an immediate CTD.

**To Reproduce**
1. Acquire a weapon with the "Soul Trap" enchantment
2. equip the weapon to either hand
3. draw the weapon/enter combat stance
4. A CTD occurs.

**Expected behavior**
The "Soul Trap" enchanted weapon plays the relevant visual effect when equipped and drawn.
**Save**
[VAE Bug - save.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9115867/VAE.Bug.-.save.zip)
This save is shortly before encountering a Soul Trap enchanted mace, the chest just past the puzzle gate contains the affected weapon.
**Crash log**

[crash-2022-07-14-18-49-53.log](https://github.com/m-vlad/Yggdrasil-VR/files/9114690/crash-2022-07-14-18-49-53.log)

**Desktop (please complete the following information):**
 - OS version: Windows 10
 - RAM:  32gb
 - CPU: Ryzen 5 3600
 - GPU: Nvidia RTX 3070
 - Storage type Yggdrasil is installed on:  SSD
 - Antivirus: Windows Defender

**Additional context**

**Comment by m-vlad** [comment]
Could you attach a save as well? easier for debugging
Thanks

**Comment by DrDollaryDoo** [comment]
just attached a zip with the save info, my apologies, first time submitting one of these reports, took me a minute to realize I needed to put the save info in a .zip file.

**Comment by m-vlad** [comment]
Fixed now, just needed to run the mod bsa through CAO :) Will be included in the next hotfix update.
