### ISSUE TITLE
FLP - Can't command followers

### ISSUE THREAD

**Issue by CameraBeard** [m-vlad/Yggdrasil-VR#6]
**Describe the bug**
Can't command mercenary follower. Hired in Windhelm via FLP (couldn't hire via vanilla method). Intended to use him as a sacrifice for Boethiah's Calling, but I noticed that when I got there I couldn't get him to complete any command. The laser pointer comes up and he recognizes that I'm trying to command him, but when I actually try to activate something he either stands there or just enters a new idle animation. I haven't tested Inigo, Lucien, Auri, or any other special follower yet so I'm not sure if the issue is exclusive to FLP managed followers.

**To Reproduce**
1. Recruit follower (Mine was a hired merc from Windhelm)
2. Open command system
3. Click on something
4. Scream internally as they ignore you

**Expected behavior**
For them to listen to the mf'in Dragonborn and DO WHAT I SAY

**Screenshots**

**Save**
[saves.zip](https://github.com/m-vlad/Yggdrasil-VR/files/9116824/saves.zip)

**Crash log**
N/A

**Desktop (please complete the following information):**
 - OS version: [e.g. Windows 11, Windows 10]
 - RAM: [e.g. 16gb, 32gb]
 - CPU: [e.g. Intel i7-9750H]
 - GPU: [e.g. Nvidia RTX 2060 Mobile]
 - Storage type Narsil is installed on: [e.g. SSD, HDD]
 - Antivirus [e.g. Windows Defender, Bitdefender]

**Additional context**

**Comment by CameraBeard** [comment]
Just an FYI, it may say you're missing an esp because I installed Jewelry Limiter, but that shouldn't be the culprit. I tried without Jewelry Limiter enabled just in case and it still didn't work.

**Comment by m-vlad** [comment]
I'll see what I can do, just an FYI though, the enchanting tree has a multiple enchantments perk that goes up quite high, if you also use multiple rings at a time the balance is gonna be even more busted than it already is. Just a fair warning.

**Comment by m-vlad** [comment]
I can't replicate this. I told him to interact with the thing, and he immediately went on to do it.
![OculusScreenshot1658008349](https://user-images.githubusercontent.com/22298459/179373306-3f56e86e-5ecf-49ec-b18d-c5c00476bc01.jpeg)
