### ISSUE TITLE
Frostfruit inn - floating props

### ISSUE THREAD

**Issue by DrDollaryDoo** [m-vlad/Yggdrasil-VR#9]
**Describe the bug**
Some firepit items, a mead cask, and a business ledger all hang in the air. the cask and ledger in particular impede NPC movement throughout the lower part of the building.

**To Reproduce**
1. Go to the Frostfruit inn (Rorikstead)
2. stuff floats

**Expected behavior**
less floating

**Comment by m-vlad** [comment]
This is likely caused by the holds patches, after checking some comments there. I'll fix them after I set up an SE version of the pack and do some further investigation.
